// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXinvUW6GOBC8y_0LsCwJthrgESgmFfTY',
    appId: '1:363475344331:web:30ff5595e66fdf3fd4344e',
    messagingSenderId: '363475344331',
    projectId: 'unicv-alert',
    authDomain: 'unicv-alert.firebaseapp.com',
    storageBucket: 'unicv-alert.appspot.com',
    measurementId: 'G-5RBX0EYHX7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBu83SfDItttk2weJcbGf7e-xmiGWq_9qU',
    appId: '1:363475344331:android:ff038d5c547b29a2d4344e',
    messagingSenderId: '363475344331',
    projectId: 'unicv-alert',
    storageBucket: 'unicv-alert.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRLHWNdBTgimfXHlkkNuTHmxeCw4o9G_U',
    appId: '1:363475344331:ios:32bc877128d3b0add4344e',
    messagingSenderId: '363475344331',
    projectId: 'unicv-alert',
    storageBucket: 'unicv-alert.appspot.com',
    iosBundleId: 'com.example.chimbinha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRLHWNdBTgimfXHlkkNuTHmxeCw4o9G_U',
    appId: '1:363475344331:ios:32bc877128d3b0add4344e',
    messagingSenderId: '363475344331',
    projectId: 'unicv-alert',
    storageBucket: 'unicv-alert.appspot.com',
    iosBundleId: 'com.example.chimbinha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXinvUW6GOBC8y_0LsCwJthrgESgmFfTY',
    appId: '1:363475344331:web:53d65aa3ac8820c0d4344e',
    messagingSenderId: '363475344331',
    projectId: 'unicv-alert',
    authDomain: 'unicv-alert.firebaseapp.com',
    storageBucket: 'unicv-alert.appspot.com',
    measurementId: 'G-K2GW4HX7N9',
  );

}